### ISSUE TITLE
Error when unpacking/running on Mac

### ISSUE THREAD

**Issue by floriankraft** [floriankraft/vocabulary-test#1]
Unpacking of "Vocabulary.Test-darwin-x64.zip" (with Keka) delivered an error:
```
Fehlercode 2 mit “p7zip”
Fataler Fehler
```

After starting the app anyway, the app shows this error:
```
Application Specific Information:
dyld: launch, loading dependent libraries
Dyld Error Message:
 Library not loaded: @rpath/Electron Framework.framework/Electron Framework
 Referenced from: /Users/USER/Downloads/*/Vocabulary Test.app/Contents/MacOS/Vocabulary Test
 Reason: image not found
```

**Comment by floriankraft** [comment]
On Linux, there was also an error, when trying to unpack the mac archive. The reason is, that the archiver I used was not able to put symlinks in the zip file.

The new build process introduced in v0.1.1 seems to resolve this issue.

So there is a great chance, that this issue is gone.

**Comment by mlemler** [comment]
The issue is gone, thanks! It works now "on my machine as well" :-)
